version: '3.8'

services:
  app:
    build: .
    restart: always
    expose:
      - 3000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    labels:
      - "traefik.enable=true"

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
